[package]
name = "packtrans-glossary-wasm"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow.workspace = true
getrandom = { version = "0.2", features = ["js"] }
serde.workspace = true
serde-wasm-bindgen = "0.6.5"
tantivy = { version = "0.25", default-features = false, features = ["lz4-compression", "columnar-zstd-compression"] }
uuid = { version = "1.23.2", features = ["js"] }
wasm-bindgen = "0.2.122"
zip = { version = "2", default-features = false, features = ["deflate"] }
