[package]
name = "packtrans-glossary"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
indicatif = "0.17"
packtrans-glossary-core = { path = "../packtrans-glossary-core" }
serde.workspace = true
serde_json.workspace = true
tantivy.workspace = true
ureq.workspace = true

[[bin]]
name = "packtrans-glossary"
path = "src/main.rs"
