[package]
name = "packtrans-glossary-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
lindera.workspace = true
lindera-dictionary.workspace = true
lindera-tantivy.workspace = true
serde.workspace = true
serde_json.workspace = true
tantivy.workspace = true
zip.workspace = true
rkyv.workspace = true
uuid.workspace = true
ureq = { workspace = true, optional = true }

[features]
default = ["native", "mmap"]
native = ["dep:ureq"]
mmap = ["tantivy/mmap"]
