[package]
name = "packtrans-glossary-builder"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
packtrans-glossary-core = { path = "../packtrans-glossary-core" }
serde_json.workspace = true
ureq = { workspace = true, features = ["json"] }
indicatif = "0.17"
zip.workspace = true

[[bin]]
name = "packtrans-glossary-builder"
path = "src/main.rs"
